name: Voltgo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Se actualizó a una versión más estable y común de Dart SDK
  sdk: '>=3.2.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
   
  # Iconos de estilo iOS
  cupertino_icons: ^1.0.8

  # Widgets y Utilidades
  pinput: ^4.0.0
  google_maps_flutter: ^2.10.1
  google_fonts: ^6.2.1
  http_parser: ^4.0.2  # Agregar esta línea

  dropdown_button2: ^2.3.9
  intl: ^0.19.0 # Se actualizó a la versión más reciente
  table_calendar: ^3.1.1 # Se actualizó a la versión más reciente
  fl_chart: ^0.68.0
  geolocator: ^12.0.0
  animate_do: ^3.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3 # Se actualizó a la versión más reciente
  http: ^1.1.0
  screenshot: ^3.0.0
  pdf: ^3.10.8
  path_provider: ^2.1.5
  device_info_plus: ^10.1.2
  url_launcher: ^6.1.11  # Para launchUrl
  share_plus: ^7.0.0     # Para Share en iOS
  open_file_plus: ^3.4.1+1
  image: ^4.5.4
  geocoding: ^3.0.0 # O la versión más reciente
  printing: ^5.6.0
  location: ^8.0.0  #
  firebase_core: ^2.15.0
  clipboard: ^0.1.3
  flutter_chat_bubble: ^2.0.2
  file_picker: ^8.0.0+1
  firebase_auth: ^4.8.0
  lottie: ^3.1.2 # O la versión más reciente
  firebase_messaging: ^14.7.10
  package_info_plus: ^8.0.0 # Para obtener la versión de la app
  uuid: ^4.4.0                 # Para generar el ID único
  flutter_dotenv: ^5.1.0 # 
  image_picker: ^1.0.7  
  flutter_image_compress: ^2.4.0
  vibration: ^1.8.1
 
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Se actualizó a la versión más reciente
  
  # --- INICIO DE LA CORRECCIÓN ---
  # El paquete del splash screen va en dev_dependencies
  flutter_native_splash: ^2.4.0 # Se actualizó a la versión más reciente
  # --- FIN DE LA CORRECCIÓN ---


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_style.json
    - assets/images/icons/
    - assets/fonts/
    - .env # <-- AÑADE ESTA LÍNEA
    # Es buena práctica ser explícito con las imágenes para evitar errores
    # - assets/images/logo_w.png
    # - assets/images/splash_background.png
    # - assets.images/backbtn.png
    
flutter_native_splash:
  color: "#19478A"
  background_image: "assets/images/inicio.png"

  android_12:
    image: "assets/images/logoAppVoltgo.png"
    icon_background_color: "#19478A"

  # --- INICIO DEL CAMBIO ---
  # 'center' muestra la imagen completa en el medio sin estirarla.
  # El color de fondo (#19478A) rellenará los espacios vacíos.
  android_gravity: center

  # 'scaleAspectFit' asegura que toda la imagen quepa en la pantalla.
  # El color de fondo rellenará los espacios vacíos.
  ios_content_mode: scaleAspectFit
  # --- FIN DEL CAMBIO ---