name: Voltgo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Iconos de estilo iOS
  cupertino_icons: ^1.0.8
  
  # FIREBASE - VERSIONES COMPATIBLES QUE FUNCIONAN JUNTAS
  firebase_core: 2.24.2
  firebase_auth: 4.15.3
  google_sign_in: 6.1.4  # Esta versión NO tiene el bug PigeonUserDetails
  firebase_messaging: ^14.7.10
  provider: ^6.1.1

  # RESTO DE DEPENDENCIAS (sin cambios)
  pinput: ^4.0.0
  google_maps_flutter: ^2.10.1
  google_fonts: ^6.2.1
  http_parser: ^4.0.2
  audioplayers: ^5.0.0
  onesignal_flutter: ^5.2.5  # o la versión más reciente disponible
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3 # Para generar el hash SHA256

  table_calendar: ^3.1.1
  fl_chart: ^0.68.0
  event_bus: ^2.0.0
  flutter_secure_storage: ^9.0.0
  geolocator: ^12.0.0
  animate_do: ^3.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  http: ^1.1.0
  screenshot: ^3.0.0
  pdf: ^3.10.8
  path_provider: ^2.1.5
  device_info_plus: ^10.1.2
  url_launcher: ^6.1.11
  share_plus: ^7.0.0
  open_file_plus: ^3.4.1+1
  image: ^4.5.4
  geocoding: ^3.0.0
  printing: ^5.6.0
  location: ^8.0.0
  clipboard: ^0.1.3
  flutter_chat_bubble: ^2.0.2
  file_picker: ^8.0.0+1
  lottie: ^3.1.2
  package_info_plus: ^8.0.0
  uuid: ^4.4.0
  flutter_dotenv: ^5.1.0  
  image_picker: ^1.0.7
  flutter_image_compress: ^2.4.0
  vibration: ^1.8.1
  intl_phone_field: ^3.2.0

# CRÍTICO: Estas versiones específicas evitan conflictos
dependency_overrides:
  google_sign_in_android: 6.1.18
  google_sign_in_ios: 5.7.4
  google_sign_in_platform_interface: 2.4.0  # Versión compatible
  google_sign_in_web: 0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/map_style.json
    - assets/images/icons/
    - assets/fonts/
    - .env

flutter_native_splash:
  color: "#19478A"
  background_image: "assets/images/inicio.png"
  android_12:
    image: "assets/images/logoAppVoltgo.png"
    icon_background_color: "#19478A"
  android_gravity: center
  ios_content_mode: scaleAspectFit